### ISSUE TITLE
作者是怎么跑通TimeGrad代码的？

### ISSUE THREAD

**Issue by whyywh** [2ySong/TimeGrad-re#1]
博主大佬您好，我是一个刚刚从事时序预测科研的小白。
我用原作者的pytorch-ts库的jupyter notebook不管是0.6.0版本还是0.7.0版本的代码总会有地方报错。
最后我找到您的代码，跑通了结果，我看你用的是 pytorch-ts，0.7.0版本， 对比原作者的jupyter 代码，您跟他的还是有很多出入，您是如何解决这些错误的？

**Comment by zysongg** [comment]
- 直接拿我的代码去跑就行了呗，我md文件里面给出了所需要所有包的版本

**Comment by whyywh** [comment]
好的，谢谢博主的代码，自己弄了一天，终于算是跑通了（但是跑不出论文中的指标）。

**Comment by zysongg** [comment]
我能跑出他的指标，差不了多少

**Comment by whyywh** [comment]
我在电力数据集上 重新设置了epoch=100，最后的CRPSsum为0.031，原论文为0.020。

**Comment by cxw20238002** [comment]
作者您好，我想问一下我在运行您的代码estimator_Diabetes = TimeGradEstimator时
<img width="375" alt="屏幕截图 2024-10-18 175458" src="https://github.com/user-attachments/assets/7e9593ca-f53b-4c7a-9080-73b7379881aa">
一直会遇到缺少参数（target_dim)或存在不支持的参数(hidden_size),您知道这是为什么吗？并且我在安装的时候pytorchts显示最新只到0.6.0版本。
